export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:3000',
  consumptionSummariesEndpointPath: '/consumption-summaries',
  energyReadingsEndpointPath: '/energy-readings',
  deviceDistributionsEndpointPath: '/device-distributions',
  comparativeConsumptionsEndpointPath: '/comparative-consumptions',
  consumptionHistoriesEndpointPath: '/consumption-histories',
  alertsEndpointPath: '/alerts',
  alertSummariesEndpointPath: '/alert-summaries',
  recommendationsEndpointPath: '/recommendations',
  usersEndpointPath: '/users',
  loginEndpointPath: '/users',
  registerEndpointPath: '/users',
  forgotPasswordEndpointPath: '/users',
  verifyEmailEndpointPath: '/users',
  resendCodeEndpointPath: '/users',
  sensorsEndpointPath: '/sensors',
  applianceProfilesEndpointPath: '/appliance-profiles',
  sensorSummariesEndpointPath: '/sensor-summaries',
  devicesEndpointPath: '/devices',
  deviceSummariesEndpointPath: '/device-summaries'
};
